name: PR

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        test: ["inmem", "postgres"]

    runs-on: ubuntu-latest
    name: Test ${{ matrix.test }}
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --name sql-stream-store-tests-postgres

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Pull Containers
      shell: bash
      run: docker pull alpinelinux/docker-cli:latest-x86_64
    - name: Build and Test
      shell: bash
      run: ./build.sh test-${{ matrix.test }}
